### ISSUE TITLE
Firo Client refuses to start

### ISSUE THREAD

**Issue by justanwar** [firoorg/firo-client#172]
```
2022-03-25T05:16:50.984Z [firo:i18n] info: setting up languages
2022-03-25T05:16:52.156Z [firo:main] info: Loading production environment at C:\Users\justanwar\AppData\Local\Programs\firo-client\resources\app.asar.unpacked\dist\electron\index.html...
2022-03-25T05:16:52.553Z error: uncaughtException: The specified module could not be found.
\\?\C:\Users\justanwar\AppData\Local\Programs\firo-client\resources\app.asar.unpacked\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node
Error: The specified module could not be found.
\\?\C:\Users\justanwar\AppData\Local\Programs\firo-client\resources\app.asar.unpacked\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at load (C:\Users\justanwar\AppData\Local\Programs\firo-client\resources\app.asar.unpacked\node_modules\node-gyp-build\index.js:21:10)
    at Object.<anonymous> (C:\Users\justanwar\AppData\Local\Programs\firo-client\resources\app.asar.unpacked\node_modules\zeromq\lib\native.js:6:43)
```

Windows 10 21H2

**Comment by justanwar** [comment]
This does not seem the case anymore with the latest version.
